export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING'
export const GET_POKEMONS_FULFILLED = 'GET_POKEMONS_FULFILLED'
export const GET_POKEMONS_REJECTED = 'GET_POKEMONS_REJECTED'

export const GET_POKEMON_BY_ID_PENDING = 'GET_POKEMON_BY_ID_PENDING'
export const GET_POKEMON_BY_ID_FULFILLED = 'GET_POKEMON_BY_ID_FULFILLED'
export const GET_POKEMON_BY_ID_REJECTED = 'GET_POKEMON_BY_ID_REJECTED'

export const GET_POKEMON_BY_NAME_PENDING = 'GET_POKEMON_BY_NAME_PENDING'
export const GET_POKEMON_BY_NAME_FULFILLED = 'GET_POKEMON_BY_NAME_FULFILLED'
export const GET_POKEMON_BY_NAME_REJECTED = 'GET_POKEMON_BY_NAME_REJECTED'

export const GET_POKEMONS_BY_TYPE = 'GET_POKEMONS_BY_TYPE'

export const GET_POKEMONS_BY_TYPE_PENDING = 'GET_POKEMONS_BY_TYPE_PENDING'
export const GET_POKEMONS_BY_TYPE_FULFILLED = 'GET_POKEMONS_BY_TYPE_FULFILLED'
export const GET_POKEMONS_BY_TYPE_REJECTED = 'GET_POKEMONS_BY_TYPE_REJECTED'

export const GET_POKEMONS_BY_SOURCE_PENDING = 'GET_POKEMONS_BY_SOURCE_PENDING'
export const GET_POKEMONS_BY_SOURCE_FULFILLED =
  'GET_POKEMONS_BY_SOURCE_FULFILLED'
export const GET_POKEMONS_BY_SOURCE_REJECTED = 'GET_POKEMONS_BY_SOURCE_REJECTED'

export const POST_POKEMON_PENDING = 'POST_POKEMON_PENDING'
export const POST_POKEMON_FULFILLED = 'POST_POKEMON_FULFILLED'
export const POST_POKEMON_REJECTED = 'POST_POKEMON_REJECTED'

export const GET_TYPES = 'GET_TYPES'

export const SORT_POKEMONS = 'SORT_POKEMONS'

export const SET_SORT = 'SET_SORT'
export const SET_FILTERS = 'SET_FILTERS'
export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const RESET_FILTERS = 'RESET_FILTERS'
