// Async actions
export const GET_POKEMONS_PENDING = 'GET_POKEMONS_PENDING'
export const GET_POKEMONS_FULFILLED = 'GET_POKEMONS_FULFILLED'
export const GET_POKEMONS_REJECTED = 'GET_POKEMONS_REJECTED'

export const GET_POKEMON_BY_ID_PENDING = 'GET_POKEMON_BY_ID_PENDING'
export const GET_POKEMON_BY_ID_FULFILLED = 'GET_POKEMON_BY_ID_FULFILLED'
export const GET_POKEMON_BY_ID_REJECTED = 'GET_POKEMON_BY_ID_REJECTED'

export const GET_POKEMON_BY_NAME_PENDING = 'GET_POKEMON_BY_NAME_PENDING'
export const GET_POKEMON_BY_NAME_FULFILLED = 'GET_POKEMON_BY_NAME_FULFILLED'
export const GET_POKEMON_BY_NAME_REJECTED = 'GET_POKEMON_BY_NAME_REJECTED'

export const POST_POKEMON_PENDING = 'POST_POKEMON_PENDING'
export const POST_POKEMON_FULFILLED = 'POST_POKEMON_FULFILLED'
export const POST_POKEMON_REJECTED = 'POST_POKEMON_REJECTED'

export const GET_TYPES = 'GET_TYPES'

// Synchronous actions
export const GET_POKEMONS_BY_SOURCE = 'GET_POKEMONS_BY_SOURCE'
export const GET_POKEMONS_BY_TYPE = 'GET_POKEMONS_BY_TYPE'
export const SORT_POKEMONS = 'SORT_POKEMONS'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const RESET_FILTERS = 'RESET_FILTERS'
